name: Download workflow

on: 
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: output

      - name: Read from file
        run: |
          # Reading from file
          cat output/output.txt