name: Upload workflow

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: mkdir -p path/to/artifact

      - run: |
          # Writing to file
          echo "Hello world" > path/to/artifact/output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact/output.txt